spring.application.name=parking-system
server.port=8080

# JSP Configuration
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

# System running in File-Based storage mode
# No Database required
